version: '3'

services:
  db:
    image: postgres:9.6
    container_name: "postgres_9_6"
    restart: no
    environment:
      - POSTGRES_PASSWORD=hzzx2024
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
