spring:
  application:
    name: gateway-server
  profiles:
    active: local
  config:
    import:
      - optional:classpath:application-${spring.profiles.active}.yaml # 加载【本地】配置
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yaml # 加载【Nacos】的配置
server:
  port: 10800

management:
  endpoints:
    web:
      exposure:
        include: "*"
